### ISSUE TITLE
Py3 Error 

### ISSUE THREAD

**Issue by piperod** [compiteing/ponywhoosh#2]
There is a problem in the middle_save. tha causes this 

```python
% python example.py runserver
Traceback (most recent call last):
  File "example.py", line 212, in <module>
    populate_database()
  File "<string>", line 2, in populate_database
  File "/Users/mac/miniconda3/envs/FPW/lib/python3.6/site-packages/pony/orm/core.py", line 413, in new_func
    try: return func(*args, **kwargs)
  File "example.py", line 208, in populate_database
    commit()
  File "<string>", line 2, in commit
  File "/Users/mac/miniconda3/envs/FPW/lib/python3.6/site-packages/pony/utils/utils.py", line 58, in cut_traceback
    return func(*args, **kwargs)
  File "/Users/mac/miniconda3/envs/FPW/lib/python3.6/site-packages/pony/orm/core.py", line 293, in commit
    cache.flush()
  File "/Users/mac/miniconda3/envs/FPW/lib/python3.6/site-packages/pony/orm/core.py", line 1620, in flush
    cache.call_after_save_hooks()
  File "/Users/mac/miniconda3/envs/FPW/lib/python3.6/site-packages/pony/orm/core.py", line 1628, in call_after_save_hooks
    obj._after_save_(status)
  File "/Users/mac/Proyectos/Jona/ponywhoosh/ponywhoosh/core.py", line 203, in _middle_save_
    writer.add_document(**attrs)
  File "/Users/mac/miniconda3/envs/FPW/lib/python3.6/site-packages/whoosh/writing.py", line 750, in add_document
    for tbytes, freq, weight, vbytes in items:
  File "/Users/mac/miniconda3/envs/FPW/lib/python3.6/site-packages/whoosh/fields.py", line 669, in index
    yield (self.to_bytes(num, shift), 1, 1.0, emptybytes)
  File "/Users/mac/miniconda3/envs/FPW/lib/python3.6/site-packages/whoosh/fields.py", line 722, in to_bytes
    x = self.prepare_number(x)
  File "/Users/mac/miniconda3/envs/FPW/lib/python3.6/site-packages/whoosh/fields.py", line 685, in prepare_number
    x = self.numtype(x)
ValueError: invalid literal for int() with base 10: '3.000000000'
```

**Comment by piperod** [comment]
Hash of the commit c764b1c106128553bc6894f4cd823909e3ea1f4b

**Comment by jonaprieto** [comment]
It seems that the commit has a lot of non-related changes, I can't figure it out where were the changes. Please, point me out where exactly you modify the source.

**Comment by piperod** [comment]
I think with source tree you could see them easier. Look for the file core.py and __init__.py, you will see on green the changes. For instance in py3 unicode is replaced by str, so instead of u'something' you will just find 'something'. Also for importing models that are in the same folder you use a dot before from .index import ...
